site_name: Conductor for Gluent Documentation
site_author: Paul Elbow
site_description: "Documentation for Conductor for Gluent"
copyright: "Â© Copyright 2020, Paul Elbow"
theme:
    name: bootstrap
extra_css:
    - css/extra.css

repo_url: https://github.com/swnerd/swnerd.github.io
repo_name: "GitHub"

